# Generated by Django 6.1.1 on 2026-09-26 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('location', models.CharField(default='Nepal', max_length=100)),
                ('period', models.CharField(default='Present', max_length=100)),
                ('is_current', models.BooleanField(default=True)),
                ('responsibilities', models.TextField(help_text='Key responsibilities separated by newlines')),
                ('technologies', models.CharField(blank=True, help_text='Comma-separated technologies used', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experiences',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Deepak Sah Kanu', max_length=150)),
                ('short_title', models.CharField(default='Django Developer', max_length=150)),
                ('extended_title', models.CharField(default='Django Developer | Full-Stack Web Developer', max_length=200)),
                ('hero_tagline', models.CharField(default='Building modern, scalable web applications with Django.', max_length=255)),
                ('alternative_tagline', models.CharField(default='Turning ideas into reliable, scalable web applications.', max_length=255)),
                ('bio_intro', models.TextField(default='I am Deepak Sah Kanu, a Django Developer and Full-Stack Web Developer focused on building modern, scalable, secure, and user-friendly web applications. I primarily work with Python and Django on the backend and HTML, CSS, JavaScript, and Bootstrap on the frontend.')),
                ('bio_extended', models.TextField(default='I enjoy transforming real-world requirements into clean, practical, and maintainable web applications. My development interests include healthcare systems, service-booking platforms, REST APIs, authentication, authorization, database-driven applications, and multi-tenant systems.')),
                ('career_goal', models.TextField(default='My goal is to grow as a professional Django / Full-Stack Developer and work on scalable real-world software systems. I specialize in advanced Django development, REST API architecture, scalable backend systems, PostgreSQL, and multi-tenant SaaS applications.')),
                ('current_company', models.CharField(default='Anjan lab company', max_length=150)),
                ('current_role', models.CharField(default='Django Developer', max_length=150)),
                ('location', models.CharField(default='Nepal', max_length=100)),
                ('email', models.CharField(blank=True, default='contact@deepaksah.dev', max_length=150)),
                ('phone', models.CharField(blank=True, default='+977 (Nepal)', max_length=50)),
                ('github_url', models.CharField(blank=True, default='https://github.com', max_length=255)),
                ('linkedin_url', models.CharField(blank=True, default='https://linkedin.com', max_length=255)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('profile_image', models.FileField(blank=True, null=True, upload_to='profile/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Personal Profile',
                'verbose_name_plural': 'Personal Profiles',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('project_type', models.CharField(help_text='e.g. Healthcare / Hospital Management System', max_length=150)),
                ('role', models.CharField(default='Django Developer', max_length=150)),
                ('summary', models.TextField(help_text='Concise summary displayed on project cards')),
                ('description', models.TextField(help_text='Detailed overview of technical architecture and concepts')),
                ('key_features', models.TextField(help_text='List key features separated by newlines')),
                ('technologies', models.CharField(help_text='Comma-separated technologies (e.g. Python, Django, DRF, PostgreSQL)', max_length=255)),
                ('live_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='projects/')),
                ('badge', models.CharField(blank=True, default='Featured', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='server', help_text='Icon identifier (e.g. server, api, tenant, database)', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Skill Category',
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proficiency', models.PositiveIntegerField(default=90, help_text='Proficiency percentage between 1 and 100')),
                ('icon_name', models.CharField(default='code', help_text='Name of icon (e.g. python, django, database, server, frontend, git, layers)', max_length=50)),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio.skillcategory')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['order', 'name'],
            },
        ),
    ]
