# Generated by Django 6.1.1 on 2026-09-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='+977 9829014425', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, default='deepakraj90054@email.com', max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github_url',
            field=models.CharField(blank=True, default='https://github.com/Deepak-sah-25', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='+977 9829014425', max_length=50),
        ),
    ]
