# Generated by Django 6.1.1 on 2026-09-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_profile_whatsapp_number_alter_profile_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(default='Bachelor in Computer Application (BCA)', max_length=150)),
                ('institution', models.CharField(default='Prime College', max_length=150)),
                ('location', models.CharField(default='Kathmandu, Nepal', max_length=150)),
                ('period', models.CharField(default='Running (3rd Year)', max_length=100)),
                ('status', models.CharField(default='Bachelor Running 3rd Year', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Coursework or key academic focus (e.g. Data Structures, Web Development, DBMS)')),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='experience',
            name='location',
            field=models.CharField(default='Kathmandu, Lalitpur, Nepal', max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Kathmandu, Lalitpur, Nepal', max_length=150),
        ),
    ]
